language: rust
rust: 1.45.2
dist: bionic
cache:
  directories:
    - $HOME/.cargo
  timeout: 1024

git:
  depth: 2
  submodules: false

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - libssl-dev
      - build-essential
      - clang-9
      - gcc-aarch64-linux-gnu
      - g++-aarch64-linux-gnu

script:
  - export TOP=$(pwd)
  - curl -LO https://www.openssl.org/source/openssl-1.1.1.tar.gz
  - tar -xzf openssl-1.1.1.tar.gz
  - cd openssl-1.1.1
  - CC=aarch64-linux-gnu-gcc ./Configure linux-aarch64 shared
  - CC=aarch64-linux-gnu-gcc make
  - cd ..
  - export OPENSSL_LIB_DIR=$TOP/openssl-1.1.1
  - export OPENSSL_INCLUDE_DIR=$TOP/openssl-1.1.1/include
  - rustup target add aarch64-unknown-linux-gnu
  - CC=gcc CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc cargo build --target=aarch64-unknown-linux-gnu --release
  - if [ -n "$TRAVIS_TAG" ]; then cp target/aarch64-unknown-linux-gnu/release/ckb ./; tar czf ckb_aarch64_${TRAVIS_TAG}.tar.gz ckb ;fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "ckb_aarch64_${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
