[package]
name = "ckb-script"
version = "0.35.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[features]
default = ["logging"]

asm = ["ckb-vm/asm"]
detect-asm = ["ckb-vm/detect-asm"]
logging = ["ckb-logger"]

[dependencies]
ckb-traits = { path = "../traits" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types"}
ckb-hash = {path = "../util/hash"}
ckb-vm = { git = "https://github.com/xxuejie/ckb-vm", rev = "255729d", default-features = false }
faster-hex = "0.4"
ckb-logger = { path = "../util/logger", optional = true }
serde = { version = "1.0", features = ["derive"] }
ckb-error = { path = "../error" }
failure = "0.1.5"
ckb-chain-spec = { path = "../spec" }
goblin = "0.2"
ckb-vm-definitions = "0.19.1"

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db" }
ckb-store = { path = "../store" }
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
tiny-keccak = "1.4"
ckb-crypto = { path = "../util/crypto"}
